Support ssh_proxy_* variables for Linux images
rainpole/packer-vsphere pull request #40
Opened 2021-09-21 13:53 UTC by sestegra

**Summary of Pull Request**
Add support of `ssh_proxy_*` variables for Linux images.

**Type of Pull Request**
- [ ] This is a bug fix.
- [X] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is a something else.
      Please describe:

**Context of the Pull Request***
https://github.com/rainpole/packer-vsphere/discussions/39

**Related to Existing Issues**
Issue Number: N/A

**Test and Documentation Coverage**
- [ ] Tests have been been completed (for bug fixes / features).
- [X] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**
- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

2021-09-21 14:17 UTC, tenthirtyam commented
@sestegra Can you confirm the following in the PR: Tests have been completed (for bug fixes/features)?

2021-09-21 15:14 UTC, sestegra commented
As discussed in thread #39, I can't test the proxy configuration with current local HTTP server.
I did some tests with my locally updated Ubuntu 20.04 user-data (using CD instead of HTTP server).

2021-09-25 18:44 UTC, tenthirtyam requested changes
Please run a 'packer fmt' against the updated 'linux-*.pkr.hcl' files to align formatting of the variables.

Ryan

2021-09-25 20:58 UTC, tenthirtyam approved these changes

2021-09-25 21:00 UTC, merged